PENDING: configs: am62lx_evm_defconfig: Remove CONFIG_SYS_BOOTM_LEN
Do not limit the maximum size of the buffer that is used to decompress
the OS image in to, this causes issue while inflating the image if image
size is greater than the buffer.

This fixes the following error while booting fitImage,
Error: inflate() returned -5
Image too large: increase CONFIG_SYS_BOOTM_LEN

Signed-off-by: Yogesh Hegde <y-hegde@ti.com>
Tested-by: T Pratham <t-pratham@ti.com>