PENDING: configs: am62x_a53_android: Include splashscreen prune config
Android does not support splashscreen because we can't load the
splashscreen file from eMMC (only SD card is supported).

The feature was partly disabled in am62x_a53_android.config but
commit 0332cc86e33e ("board: ti: am62x: evm: Update simple-framebuffer node in device-tree")
introduced linking errors:

    aarch64-none-linux-gnu-ld.bfd: board/ti/am62x/evm.o: in function `ft_board_setup':
    u-boot/board/ti/am62x/evm.c:92: undefined reference to `fdt_simplefb_enable_and_mem_rsv'
    make: *** [Makefile:1766: u-boot] Error 139

Fix the above linking error by including am62x_evm_prune_splashscreen.config.

Signed-off-by: Mattijs Korpershoek (TI.com) <mkorpershoek@baylibre.com>
Reviewed-by: Devarsh Thakkar <devarsht@ti.com>
Signed-off-by: Maxime Fournier (TI.com) <mfournier@baylibre.com>