include: Use CONFIG_IS_ENABLED(VIDEO) for fdt_add_fb_mem_rsv()
IF CONFIG_VIDEO is enabled, using IS_ENABLED() causes a build failure

../common/fdt_support.c: In function âfdt_add_fb_mem_rsvâ:
../common/fdt_support.c:1983:15: error: âgd_tâ
{aka âvolatile struct global_dataâ} has no member named âvideo_bottomâ
 1983 |         if (gd->video_bottom == gd->video_top)

So use CONFIG_IS_ENABLED(VIDEO) to fix it.

Signed-off-by: Sukrut Bellary <sbellary@baylibre.com>